--Teste PRC_ISNERE_FUNCIONARIO

EXEC PRC_INSERE_FUNCIONARIO('PAULO','CHAVES','PAULOCHAVeS2','777777777',SYSDATE,'IT_PROG',9000,NULL,103,60);

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';

SELECT * FROM JOBS WHERE JOB_ID = 'IT_PROG';

--Teste PRC_ATUALIZA_SALARIO

EXEC PRC_ATUALIZA_SALARIO(207,8000);

--Teste PRC_TRANSFERE_FUNCIONARIO

EXEC PRC_TRANSFERE_FUNCIONARIO(210,90);

SELECT * FROM EMPLOYEES WHERE LAST_NAME = 'CHAVES';

SELECT * FROM JOB_HISTORY;

--Teste FNC_CALCULA_MEDIA_SALARIAL

SELECT FNC_CALCULA_MEDIA_SALARIAL(60) FROM DUAL;

SELECT SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 60;

--Teste FUN_OBTEM_NOME_COMPLETO

SELECT FUN_OBTEM_NOME_COMPLETO(210)FROM DUAL;

--Teste FUN_VERIFICA_HIERARQUIA

SELECT FUN_VERIFICA_HIERARQUIA(210,210)FROM DUAL;

--Teste PRC_GERA_RELATORIO_POR_DEPARTAMENTO

EXEC PRC_GERA_RELATORIO_POR_DEPARTAMENTO(60);

--Teste PRC_VALIDA_SALARIO_ACIMA_DA_MEDIA_DEP

EXEC PRC_VALIDA_SALARIO_ACIMA_DA_MEDIA_DEP(60);

SELECT * FROM SALARIOS_ACIMA_DA_MEDIA;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 60 AND SALARY > FNC_CALCULA_MEDIA_SALARIAL(60);

UPDATE EMPLOYEES SET SALARY = 9200 WHERE EMPLOYEE_ID = 207;