--Teste PRC_ISNERE_FUNCIONARIO

EXEC PRC_INSERE_FUNCIONARIO('PAULO','CASTRO','PAULOCHAVES','777777777',SYSDATE,'IT_PROG',500000,NULL,103,60);

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';

SELECT * FROM JOBS WHERE JOB_ID = 'IT_PROG';

--Teste PRC_ATUALIZA_SALARIO

EXEC PRC_ATUALIZA_SALARIO(207,8000);