DROP TABLE LOG_SALARIO_EMPREGADOS;

CREATE TABLE LOG_SALARIO_EMPREGADOS(
    LOG_ID              NUMBER NOT NULL,
    TIPO_ACAO           VARCHAR2(1),
    DATA_ALTERACAO      DATE,
    EMPLOYEE_ID         NUMBER NOT NULL,
    SALARIO_ANTES       NUMBER(8,2),
    SALARIO_DEPOIS      NUMBER(8,2),
    USUARIO_ALTERACAO   VARCHAR2(100)
);

CREATE SEQUENCE SEQ_LOG_SALARIO_EMPREGADOS
MINVALUE 1
INCREMENT BY 1
NOCACHE
NOORDER 
NOCYCLE  
NOKEEP  
NOSCALE  
GLOBAL;

DESC EMPLOYEES;

DROP TABLE LOG_JOB_HISTORY;

CREATE TABLE LOG_JOB_HISTORY(
    LOG_ID              NUMBER NOT NULL,
    TIPO_ACAO           VARCHAR2(1),
    DATA_ALTERACAO      DATE,
    EMPLOYEE_ID         NUMBER NOT NULL,
    JOB_ID_ANTES        VARCHAR2(10),
    JOB_ID_DEPOIS       VARCHAR2(10),
    DEPARTMENT_ID_ANTES NUMBER(4),
    DEPARTMENT_ID_DEPOIS NUMBER(4),
    USUARIO_ALTERACAO   VARCHAR2(100)
);

CREATE SEQUENCE SEQ_LOG_JOB_HISTORY
MINVALUE 1
INCREMENT BY 1
NOCACHE
NOORDER 
NOCYCLE  
NOKEEP  
NOSCALE  
GLOBAL;

COMMIT;

CREATE TABLE SALARIOS_ACIMA_DA_MEDIA(
    EMPLOYEE_ID     NUMBER(6),
    NOME_COMPLETO   VARCHAR2(100),
    JOB_ID          VARCHAR2(10),
    DEPARTMENT_ID   NUMBER(4),
    SALARY	        NUMBER(8,2)
);

CREATE UNIQUE INDEX IDX_SACD_EMPLOYEE_ID ON SALARIOS_ACIMA_DA_MEDIA(EMPLOYEE_ID);

CREATE TABLE SALARIOS_ABAIXO_DO_PERMITIDO(
    EMPLOYEE_ID     NUMBER(6),
    NOME_COMPLETO   VARCHAR2(100),
    JOB_ID          VARCHAR2(10),
    DEPARTMENT_ID   NUMBER(4),
    MIN_SALARY	    NUMBER(8,2),
    SALARY	        NUMBER(8,2)
);

CREATE UNIQUE INDEX IDX_SADP_EMPLOYEE_ID ON SALARIOS_ABAIXO_DO_PERMITIDO(EMPLOYEE_ID);
