DROP TABLE LOG_SALARIO_EMPREGADOS;

CREATE TABLE LOG_SALARIO_EMPREGADOS(
    LOG_ID              NUMBER NOT NULL,
    TIPO_ACAO           VARCHAR2(1),
    DATA_ALTERACAO      DATE,
    EMPLOYEE_ID         NUMBER NOT NULL,
    SALARIO_ANTES       NUMBER(8,2),
    SALARIO_DEPOIS      NUMBER(8,2),
    USUARIO_ALTERACAO   VARCHAR2(100)
);

CREATE SEQUENCE SEQ_LOG_SALARIO_EMPREGADOS
MINVALUE 1
INCREMENT BY 1
NOCACHE
NOORDER 
NOCYCLE  
NOKEEP  
NOSCALE  
GLOBAL;

DESC EMPLOYEES;