CREATE OR REPLACE VIEW TOP_3_SALARIOS_POR_DEPARTAMENTO AS(
    SELECT * FROM
        (SELECT 
            FIRST_NAME,
            LAST_NAME, 
            SALARY,
            DEPARTMENT_ID, RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS RANK 
         FROM 
            EMPLOYEES)
    WHERE RANK <= 3
);