CREATE OR REPLACE FUNCTION FUN_VERIFICA_HIERARQUIA(pEMPLOYEE_ID1 EMPLOYEES.EMPLOYEE_ID%TYPE, pEMPLOYEE_ID2 EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN NUMBER
IS
    vDEPARTMENT_ID  EMPLOYEES.DEPARTMENT_ID%TYPE;
    vMANAGER        EMPLOYEES.MANAGER_ID%TYPE;
BEGIN
    SELECT
        DEPARTMENT_ID,
        MANAGER_ID
    INTO
        vDEPARTMENT_ID,
        vMANAGER
    FROM
        EMPLOYEES
    WHERE
        EMPLOYEE_ID = pEMPLOYEE_ID1;
    
    IF pEMPLOYEE_ID2 = vMANAGER
    THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'EMPPREGADO NAO ENCONTRADO');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;