SELECT * FROM JOBS;

CREATE OR REPLACE FUNCTION FUN_VALIDA_SALARIO(pJOB_ID EMPLOYEES.JOB_ID%TYPE,pSALARY EMPLOYEES.SALARY%TYPE)
RETURN NUMBER
IS
    vMAX_SALARY JOBS.MAX_SALARY%TYPE;
    vMIN_SALARY JOBS.MIN_SALARY%TYPE;
BEGIN
    
    SELECT
        MIN_SALARY,
        MAX_SALARY
    INTO
        vMIN_SALARY,
        vMAX_SALARY
    FROM
        JOBS
    WHERE
        JOB_ID = pJOB_ID;
    
    IF pSALARY BETWEEN vMIN_SALARY AND vMAX_SALARY
    THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
    
    
    
EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'DEPARTAMENTO ' || pJOB_ID || ' NÃO EXISTE');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002,'ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;