CREATE OR REPLACE FUNCTION FUN_OBTEM_NOME_COMPLETO(pEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN VARCHAR2
IS
    vNOME_COMPLETO VARCHAR2(100);
BEGIN
    SELECT
        FIRST_NAME || ' ' || LAST_NAME
    INTO
        vNOME_COMPLETO
    FROM
        EMPLOYEES
    WHERE
        EMPLOYEE_ID = pEMPLOYEE_ID;
        
    RETURN vNOME_COMPLETO;

EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'EMPPREGADO NAO ENCONTRADO');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE: ' || SQLCODE || SQLERRM);   
END;