CREATE OR REPLACE FUNCTION FNC_CALCULA_MEDIA_SALARIAL(pDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE)
RETURN NUMBER
IS
    vMEDIASALARIAL EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT
        AVG(SALARY)
    INTO 
        vMEDIASALARIAL
    FROM
        EMPLOYEES
    WHERE
        DEPARTMENT_ID = pDEPARTMENT_ID;
    
    RETURN vMEDIASALARIAL;

EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'DEPARTAMENTO NAO ENCONTRADO');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;