CREATE OR REPLACE PROCEDURE PRC_ATUALIZA_SALARIO(pEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE, pSALARY EMPLOYEES.SALARY%TYPE)
IS
BEGIN
    UPDATE EMPLOYEES
        SET SALARY = pSALARY
    WHERE
        EMPLOYEE_ID = pEMPLOYEE_ID;

EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20002,'EMPREGADO NÃO ENCONTRADO ' || pEMPLOYEE_ID);
END;