CREATE OR REPLACE PROCEDURE PRC_TRANSFERE_FUNCIONARIO(pEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE, pDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE)
IS
    vMANAGER_ID EMPLOYEES.MANAGER_ID%TYPE;
BEGIN
    SELECT
        MANAGER_ID
    INTO
        vMANAGER_ID
    FROM
        DEPARTMENTS
    WHERE
        DEPARTMENT_ID = pDEPARTMENT_ID;

--Caso o departamento ainda nao tenha um manager, ele sera definido como o presidente ate que seja adcionado
    IF
        vMANAGER_ID IS NULL THEN
            vMANAGER_ID := 100;
    END IF;
    
    UPDATE 
        EMPLOYEES
    SET
        DEPARTMENT_ID   = pDEPARTMENT_ID,
        MANAGER_ID      = vMANAGER_ID
    WHERE 
        EMPLOYEE_ID = pEMPLOYEE_ID;

EXCEPTION
    WHEN NO_DATA_FOUND
    THEN
        RAISE_APPLICATION_ERROR(-20002,'ID EMPREGADO OU DEPARTAMENTO NAO ENCONTRADO');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002,'ERRO ORACLE: ' || SQLCODE || SQLERRM );
END;