CREATE OR REPLACE TRIGGER TRG_VALIDA_EMAIL_UNICO
BEFORE INSERT OR UPDATE OF EMAIL ON EMPLOYEES
FOR EACH ROW
DECLARE
    vVALIDA_EMAIL NUMBER(1);
    VALIDA_EMAIL_EXCEPTION EXCEPTION;
BEGIN

    vVALIDA_EMAIL := FUN_VALIDA_EMAIL(:NEW.EMAIL);
    
    IF vVALIDA_EMAIL = 1
    THEN
        RAISE VALIDA_EMAIL_EXCEPTION;
    END IF;
    
EXCEPTION
    WHEN VALIDA_EMAIL_EXCEPTION
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'EMAIL JA UTILIZADO');
END;