CREATE OR REPLACE TRIGGER TRG_VALIDA_SALARIO
    BEFORE INSERT OR UPDATE OF SALARY ON EMPLOYEES
    FOR EACH ROW
DECLARE
    vVALIDA_SALARIO NUMBER(1);
    VALIDA_SALARIO_EXCEPTION EXCEPTION;
BEGIN
    
    vVALIDA_SALARIO := FUN_VALIDA_SALARIO(:NEW.JOB_ID,:NEW.SALARY);
    
    IF vVALIDA_SALARIO = 0
    THEN
        RAISE VALIDA_SALARIO_EXCEPTION;
    END IF;

EXCEPTION
    WHEN VALIDA_SALARIO_EXCEPTION
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'SALARIO NAO PERMITIDO PARA O CARGO: ' || :NEW.JOB_ID);
END;
